freq: 50.0
sensor_timeout: 1.0
odom_used: true
imu_used: true
vo_used: false
gps_used: true
debug: false
self_diagnose: false

# Odometry configuration of Odometry message from navsat_transform_node:

odom0: /odometry/gps
odom0_differential: false

odom0_config: [true, true, false,
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]

