footprint: [[0.21, 0.22], [0.21, -0.22], [-0.21, -0.22], [-0.21, 0.22]]



# http://wiki.ros.org/costmap_2d/hydro/staticmap
static_layer:
  unknown_cost_value: -1
  lethal_cost_threshold: 100
  map_topic: map
  first_map_only: false
  subscribe_to_updates: false
  track_unknown_space: true
  use_maximum: false
  trinary_costmap: true

# http://wiki.ros.org/costmap_2d/hydro/obstacles
obstacle_layer:
  max_obstacle_height: 1
  min_obstacle_height: 0.01
  obstacle_range: 2.5
  raytrace_range: 3.0
  track_unknown_space: true
  footprint_clearing_enabled: true
  combination_method: 1

  observation_sources: laser


  laser:
    sensor_frame: laser
    data_type: LaserScan
    topic: scan
    clearing: true
    marking: true
    min_obstacle_height: 0.001
    max_obstacle_height: 1
    inf_is_valid: false


#   observation_sources: scan

#   scan:
#     topic: robot1/scan
#     observation_persistance: 0.0
#     expected_update_rate: 0.30
#     data_type: LaserScan
#     clearing: true
#     marking: true
#     min_obstacle_height: 0.1
#     max_obstacle_height: 0.3
#     inf_is_valid: false

# http://wiki.ros.org/costmap_2d/hydro/inflation
inflation_layer:
  inflation_radius: 0.4
  cost_scaling_factor: 30.0
